yagomichalak/sloth-bot

cogs/teacherfeedback.py

Previously, Moderators couldn't join on-going classes unless they had the Studying <language> role. Often times teachers would DM me asking for me to come diffuse a situation in the lesson voice channel and I had to first assign the studying <language> role to myself which took up precious time. With this update, moderators can now join any lesson VC that they want, whether they have the Studying <language> role or not. This will hopefully speed up response times and make moderating easier.

Add ability for mods to join lessons

---

cogs/createdynamicroom.py

Users with no roles will no longer make the bot put out message errors

Dynamic room no roles users fix

---

cogs/eventmanagement.py
sql/create_dynamic_room_setup.sql

Unlike the other events, Cinema events have no permissions related to the role "Cinema club"; Added indonesian flag along with the name of two indonesian Dynamic rooms.

ADD perms to 'cinema club' role under 'create_event' and Indonesian flag in dynamic rooms

---

cogs/moderation.py

After fixing it so muted users cannot pick roles, the user has to be removed from the database first before they can have their roles back. This is because the event cancels every role update if the user is in the muted database.

Fixed so the temp unmute works again

---

cogs/moderation.py

Currently, nitro kick doesn't work with moderators when 3 or more mods click on the nitro kick confirmation.
Looks like a basic fix.

fix: possibly fixes the nitro kick confirmation problem

---

cogs/moderation.py

Both nitrokick and ban commands where not working since they both user the parameter *delete_message_days* in the guild.ban() command, which is deprecated since version 2.1. Changed it to *delete_message_seconds* with the days equivalents in seconds.

fix: Fixed nitrokick and ban commands

---

cogs/moderation.py

yeah idk why but in my local bot i had to substract 1 hour lol

fix: Fixed bug that caused first 1h timeout not to apply

---

cogs/moderation.py

- removal of timeout role from expired timeouts now works as intended
- also decreased the loop time from 10m to 3m

fix: timeout role not being removed

---

cogs/moderation.py

this should make the dm that gets sent more future-proof and dumbass-proof
- fixed the muted channel id
- changed the order of messages being sent, _some idiots can't read the first message_

fix: muted chat dm

---

cogs/modactivity.py
extra/moderation/modactivity.py

Also added two staff commands:
track_mod_activity -> To add the missing moderators to the ModActivity table ( this command can be removed afterwards ).
untrack_mod_activity -> To stop tracking a moderator's activity if they are no longer part of the team.

Improved modrep and fixed mods not showing on command when the data is reset.

---

cogs/teacherfeedback.py

- now, teachers can create "speaking" and "revision" classes as well through the create classroom system. 
- you're welcome, teachers!
couldn't test this one in a local environment...
in theory, should work just fine though as there are only minimal addition into the create classroom system.

refactor: new class types added

---

cogs/teacherfeedback.py

- before, for some reason, it was being sent to the bots and command channel
- now, reward logs will be sent to the reward logs thread
(sorta) tested and (hopefully) works.

refactor: reward logs has its own thread now

---

cogs/moderation.py
extra/view.py

sort of a test about the easy warn command thingy we talked about a while ago
- now, the warn commands start up a sequence when executed without any arguments
- asks for id, makes you select a rule from a drop-down menu and asks for the reason of warning

feat: "easier" version of the warn command

---

cogs/teacherfeedback.py

- quick fix for a certain bot not being able to connect into class voice channels
not tested but should work.

fix: connect perm for certain bot used in classes

---

cogs/moderation.py
cogs/show.py

- mostly because of that one staff member who KEEPS trying to use these aliases (and fails, lol)
- also yoinked one of the aliases from the wikipedia command (w)
necessary checks have been made, should work

refactor: new (shorter) aliases for warn commands

---

cogs/moderation.py

- it wasn't checking for the situation where if user has both event manager and bot sub, now it does

fix: bot sub check for event managers

---

cogs/moderation.py

- now, lesson managers can also use the infraction command
- both lesson and event managers are now limited to use the command in their respective threads

refactor: lesson managers perm for infraction command and new limitations

---

cogs/teacherfeedback.py

damn you sql
- reward embed will no longer only say "1 to go" and actually show the amount of students left in the reward list
tested on a small scale and works.
we'll see what happens after testing on the server.

fix: long-awaited "1 to go" fix

---

cogs/moderation.py

users with this role was basically untouchable by the mute command, good thing that they didn't know this
- bot will not try to remove integration roles anymore
not tested, hopefully works.

fix(mute): integration roles break mute command

---

cogs/moderation.py

apparently, webhook messages count as bot messages
- ban appeal infraction lists should pop up now

fix(mod): fix bot-webhook message inconsistency

---

cogs/moderation.py

- in the infraction list, we're back to ordering from oldest to newest
- no longer automatically bans on the 4th warn point

refactor(infr): infraction changes

---

cogs/moderation.py

we delete it nevertheless, so here's one less thing for us to do
- delete the invite after timing out the user

refactor(invite): remove invite links

---

cogs/aspirantsactivity.py
cogs/bootcamp.py
cogs/communication.py
cogs/embeds.py
cogs/eventmanagement.py
cogs/modactivity.py
cogs/moderation.py
cogs/reportsupport.py
cogs/slothcurrency.py
cogs/tools.py
cogs/voicemanagement.py
extra/minigames/whitejack/whitejack.py
extra/reportsupport/applications.py

- mod couldn't warn each other for some reason, it's fixed (or maybe not, we'll see)
- close application command was only usable by lesson managers, now it's usable by staff and event managers as well
- new scam link added to the list
- internal staff manager role variable name is changed
mostly tested and works.

fix: staff command fixes and other fixes 

---

cogs/reportsupport.py

cleaning that ai slop is probably going to be the worst cleanup experience for quite some time
- cache used by apply forms that got deleted by mistake is added back

fix(apply): cache got deleted by mistake

---

cogs/reportsupport.py

some forgotten fixes from the last batch
- case logs will no longer include staff cases, for privacy reasons
- case channel names are now all the same, forgot to change one of them
mostly tested, should work.

fix(case): channel name and log fixes
