yagomichalak/sloth-bot

- cogs/tools.py
- main.py
- todo
z!inrole perms increased to mods; z!help error message; 'todo' file deleted
> UPDATED @everyone pings

- extra/moderation/watchlist.py
Added support for mention multiples members when using the command z!watchlist
> add mention to multiple users in z!watchlist

- cogs/moderation.py
- extra/moderation/userinfractions.py
- extra/moderation/watchlist.py
- Mention to multiple members when removing them from the watchlist
- Aliases **wl** for watchlist and **uwl** for unwatchlist
- Removed confirmation for the command unwatchlist
- Added command edit_infraction by an infraction id
> changes in unwhatchlist mentions and added command edit infraction

- cogs/createdynamicroom.py
- sql/create_dynamic_room_setup.sql
now each room can have a custom expiration time
> category fixes

- cogs/createdynamicroom.py
- sql/create_dynamic_room_setup.sql
Disclaiming the fact I added a message to see if the tasks are running correctly
> Fixed room self deletion

- cogs/games.py
- extra/minigames/view.py
- extra/random/json/flag_game.json
The game ends when four timeouts in a row
> Flag quiz timeout

- extra/minigames/blackjack/blackjack_game.py
- extra/minigames/view.py
> IMPROVED blackjack minigame

- extra/minigames/blackjack/blackjack_game.py
> IMPROVED blackjack minigame logic again because last commit didn't work

- extra/minigames/blackjack/blackjack_game.py
> FIXED blackjack (im'a dumball)

- cogs/show.py
z!rule should show correct amount and, also, return message for possible languages.
> Fixed rule amount for individual rules

- cogs/eventmanagement.py
- cogs/teacherapi.py
host demotion command, event_manager perms, typos
> events and typos

- cogs/eventmanagement.py
additional perm broke events' creation
> FIX create_event not working

- cogs/reportsupport.py
- extra/modals.py
Fixed so the teacher application will ping Prisca instead of muffin in the teacher application channel.
> Un-muffined teacher application ping, and added Prisca ping instead

- cogs/reportsupport.py
Exactly what the title describes.
> change: now only admins can see the staff reports and elijah gets pinged

- cogs/prestige.py
Added my command with some cool staff and server emojis, I hope it's not a problem.
> Added cafone's command (I hope it works)

- cogs/moderation.py
Revamped the whole infraction system with the next features:
- Separated warn types in lwarn (light, former watchlist), warn (serious) and hwarn (heavy)
- Automated the timeout process, will timeout users the necessary ammount of time once the warn is given
- Used different colors for the warns' embeds
> Revamped infraction system

- cogs/moderation.py
Fixed timeout time, fixed bot automatic message with timeout time and reason, implemented automatic adding and removing of timeout role, changed embed color to the mod's main color.
NECESSARY THING:
In order to make the bot work, the creation of a "Timed Out" role is necessary on top of normal roles. Its id must be written in the project's .env file as shown:
TIMEDOUT_ROLE_ID = 123
> fix: Fixed timeout time and other things

- cogs/prestige.py
I've been told to make a command, test it and send a pull request for it. Here it is.
> feat: hodja's command

- cogs/prestige.py
- cogs/teacherfeedback.py
- extra/modals.py
- changed teacher feedback prompt from 10m to 24h
-  changed apply to moderator input from "What's your English level? " to "Languages spoken and proficiency level?"
> Changed teacher feedback prompt timeout and apply to mod input

- cogs/prestige.py
Another prestige command.
Tested and works.
> feat: hiba command

- cogs/social.py
Lowered from 60 seconds to 6 seconds.
Tested and works.
> change: nickname change cooldown lowered

- cogs/reportsupport.py
- extra/reportsupport/applications.py
Just some small changes on the messages that are being sent to the user and to the interview thread.
Tested and works.
> refactor: application interview messages

- cogs/moderation.py
- cogs/social.py
- extra/moderation/userinfractions.py
- extra/moderation/watchlist.py
- extra/view.py
integrated watchlist is finally ready. also reworked the infractions, ui command and made some other small changes and fixes.
extensively tested and works.
> feat: integrated watchlist

- cogs/moderation.py
another style change, this time it should work without problems. we're more hopeful about it this time.
also fixes a problem about old infraction which were given ex-staff members who left the server.
we're probably gonna do another style change pr at some point in the close future.
> refactor/fix: infraction list style change

- cogs/moderation.py
- extra/view.py
also includes a slight label change for one of the buttons in z!ui.
> fix: watchlist edits sending users an edited reason dm

- cogs/createsmartroom.py
until further notice, we are temporarily disabling the galaxy room creation options.
> refactor: galaxy rooms (temporarily) disabled

- cogs/VoiceChannelActivity.py
- cogs/moderation.py
- cogs/social.py
- extra/view.py
we just added some analyst perms to commands for them to use. (ui, infr, snipe, vh)
> refactor: some perms for analysts

- cogs/tools.py
more and more and more
tested and works. (at least for the current list of rooms)
> refactor: more commands for analysts

- cogs/reportsupport.py
one of the perms were getting overwritten by the code, it's also added through the code now.
> fix: mod perms were different than category

- cogs/reportsupport.py
this was an old pr that we still needed, made some changes and cleaned it up a bit
> refactor: witnesses now get a dm when allowed

- cogs/moderation.py
- cogs/reportsupport.py
- cogs/tools.py
- extra/reportsupport/openchannels.py
- automatic case deletion is reduced down from 24h to 19h
- snipe is no longer deleting the last message (temp fix)
- small styling change on the interview thread message
- follow command perm for analysts
> refactor: small changes

- cogs/moderation.py
- watchlist will no longer show up in the infraction list when it's used by anyone else other than staff members
- we also disabled it in the muted chat (and maybe more channels in the future)
> refactor: watchlist privacy changes

- cogs/moderation.py
- new commands for easily adding or removing secret agents
- only works in the secret agents channel unless you're admin
> feat: secret agent commands

- cogs/moderation.py
i'm gonna scream 
(#145, line 67)
i don't even have to test this one...
> fix: FOR THE LOVE OF EVERYTHING THAT IS HOLY

- cogs/reportsupport.py
because their tasks are not working, this is a temporary command for:
- checking and closing cases that surpassed the 19h limit
- checking and removing timeout roles from people who served their timeout time
tested and works... hopefully same thing can be said on the main server.
> feat: temp check command

- cogs/reportsupport.py
> fix: keep messing up in the same part

- extra/useful_variables.py
- now we'll just use the id from the env file instead of inserting the id manually, so that any id changes in the future would not require a manual change in the code
> fix: report channel was unknown

- cogs/moderation.py
- as requested
- (pr sent prior to this was about an unfinished little change, so here we go again)
> style: changed the question channel clear message

- cogs/embeds.py
- you're welcome, lesson managers!
> refactor: embed command for lesson managers

- extra/reportsupport/applications.py
- for some reason it requires reactions from mods rather than lesson managers, fixed
not really needs testing, should work
> fix: teacher application perms

- extra/modals.py
- now instead of saying "when we need a new mod", they give the correct application type in the response
not really needs testing, should work
> fix: application responses now give correct ones

- cogs/moderation.py
- added auto ban into the warn weight map and warn callback
- changed the warn weight map to comply with the new warn system
(i might revisit the whole thing in the future, it's a lil' rushed atm)
> refactor: warn system changes

- cogs/moderation.py
- extra/moderation/firewall.py
**we so back**
- the main firewall stuff are there, bypass is also working
- a new command for account age limit change that admins can use is also added
mostly tested and works.
> feat: firewall resurrection

- README.md
- scripts/env-setup.bat
- scripts/env-setup.sh
Add venv scripts for Linux/Mac and Windows so new contributors don't have to deal with errors.
> feat: Add venv scripts for Linux/Mac and Windows

- cogs/moderation.py
- extra/moderation/firewall.py
- now the reason is changeable and there is also an extra kick response mode
> feat: response type and reason command/options

- cogs/moderation.py
- any infracton command that asks for a reason now asks for a minimum limit of 16 characters to successfully send the infraction
> refactor: minimum character limits for reasons

- cogs/prestige.py
> feat: Add jelly command and added a hiba string

- cogs/teacherfeedback.py
- lesson manager role is now allowed to use the close_class command
not tested, should work
> refactor: lesson managers added to command

- cogs/moderation.py
oopsie, forgot the add the same bypass stuff to ban command as well
- added the reason bypass to ban command
> refactor: forgotten ban reason bypass

- cogs/moderation.py
- now it's a gif we found while goofing around, request from cosmos
works, just a link change
> refactor: change the broken muted.png

- cogs/moderation.py
- from now on, infraction removals will get logged to the mod log
> refactor: infraction remove logs

- cogs/moderation.py
- event managers can now use the infraction command
- special request from lemon
> refactor: event managers infr perm

- cogs/moderation.py
- there were some forgotten bypasses for the char limits of hackban and edit infraction 
- (and one more i've forgotten while writing this)
**should work™️**
> fix: forgotten admin bypasses for other limits

- cogs/moderation.py
- from now on, infractions can only be removed by the staff member who issued it in the first place 
- (or staff managers and admins, obviously)
> refactor: infraction remove limitations

- cogs/moderation.py
- extra/moderation/userinfractions.py
- no longer counting expired warns in the infraction list
> refactor: not counting expired warns

- extra/modals.py
we think that 4000 is a bit too much, but you do you discord
- motivation part of the teacher app now has a 1000 character limit
> refactor: max char limit to part of teacher app

- cogs/eventmanagement.py
> fix: productivity cam check

- cogs/misc.py
ah the things gabs make me do...
- one for macacos and one for monkeys o_O
> feat: requested goofy ping commands

- cogs/misc.py
bruh
- brazilian id's will be added later on
> refactor: goofy command changes

- cogs/misc.py
hopefully
- id's added, last requests handled
> refactor: final changes to the goofy commands

- cogs/reportsupport.py
shut your trap, you "work in progress" ahh ai mod assistant
- will skip ai part if the message is from the muted chat
not tested, should work.
> fix: disable ai from talking in muted chat

- cogs/reportsupport.py
- Added a new prompt to the Claude AI, now it will retrieve its system from an external source.
- The AI only sends a summary to the mod that mentions the Sloth bot.
- Fixed a bug that enabled end-users to ping the sloth both and receive a DM.
- Fixed a bug that was causing the bot to not stop sending messages after a mod or admin responded the channel.
- Fixed a bug that caused the bot to send message in other channels from the case_cat_id.
- Updated the AI to get its prompt system from Google Drive. 
- Made the AI know what is the prinicipal native language of the user sending the report.
> Improved the Claude AI system and fixed bugs

- cogs/reportsupport.py
Fixed a bug where mods could see the staff reports. Adjusted the AI summary system so it can be requested by any mod at any time by pinging the bot.
> Improvement of report-support system

- cogs/reportsupport.py
- cogs/teacherfeedback.py
- now it'll take a week before the interview thread gets archived
- messages from class vc now count as well
> refactor/fix: interview auto-archive durations and class vc message count fix

- cogs/moderation.py
- cogs/reportsupport.py
- extra/modals.py
- extra/view.py
- removed "app" command
- removed ReportSupportView and replaced to 3 new (ReportView, PremiumView, ApplyView)
> New Embed Report-Support

- extra/view.py
- "Apply for Staff" to  "Apply for staff positions"
- Added embed for "Frog Catcher" button
> Placeholder, FrogCatcher embed

- cogs/teacherfeedback.py
big brain time
- new class type "comprehension" added 🧠
not tested, should work
> feat: comprehension class type

- cogs/moderation.py
- categories are gone, list orders from latest to oldest and should be more readable (hopefully)
> refactor: infraction list makeover

- cogs/analytics.py
- built-in joined-left logs for the bot with role information
> feat: joined-left logs

- extra/view.py
- fix "apply_to_analyst_debugget" to "apply_to_analyst_debugger";
- add new select with emoji for "Debate Organizer".
> Application view for 'Debate Organizer'

- cogs/analytics.py
- it will now calculate from years to seconds and show them dynamically instead of only showing up to days
> refactor: more detailed account age calculation for join logs

- cogs/moderation.py
- extra/moderation/watchlist.py
- edits to every single infraction with logs to look the same with the new infractions format
mostly tested and hopefully fully works.
> refactor: infraction log consistency

- cogs/reportsupport.py
- extra/modals.py
- extra/reportsupport/applications.py
- extra/view.py
> feat: Add application for Debate Organizer

- extra/view.py
does what it says
- debate organizer moved to be the last option, as requested
not tested, should work.
> refactor(ui): change order of applications

- cogs/moderation.py
- whenever there is a new ban appeal in the ban appeal channel, bot will send the banned user's infraction list
minimally tested, should work.
> feat(mod): send infraction list for ban appeals

- cogs/moderation.py
now we can double mute the muted users, hurray!
- silence command for times where we need to temporarily timeout braindead muted users
- also, unsilence command for early removal of that timeout
> feat(mod): silence command for muted chat

- cogs/moderation.py
- it was being removed by the muted role check, it won't anymore
> fix(silence): timeout role won't get removed

- cogs/modactivity.py
- extra/moderation/modactivity.py
- database backends for new settings that will be used for quickly changing and managing the minimum voice and text activity limits for mods
- new settings for the mod activity list, minimum voice time and text message limits that can be easily changed through new commands
- and some extra fixes
> feat(mod): configurable limits for mod activity

- cogs/moderation.py
- cogs/reportsupport.py
once again, all i can say is bruh
- timeout checks should work once again, hopefully
tested and works. these fixes usually barely work on the main server though.
> fix(timeout): timeout checks no longer fail

- cogs/prestige.py
- remade hodja command
- added message cleaner to commands
- changed gabs id to the current one
- removed older prestige commands that are no longer relevant
> refactor(prestige): general cleanup of prestige commands

- extra/view.py
- teacher is at the top of the application list now
- also disabled applications that are not available as of now
> refactor(applications): application order changed

- cogs/moderation.py
- cogs/prestige.py
- cogs/reportsupport.py
- it's now possible to allow management roles as a whole to cases
- staff managers are now allowed to unban
- disabled lwarn and hwarn commands
- invite links will get you a 30 minute timeout instead of a mute
- hackban will now also behave like how the ban command behaves (i forgot)
- case number will get logged in the closed case logs
- timeout duration will also get logged in the warn logs
- new nitrokick alias
> feat/refactor: more of the requested stuff in bulk

- cogs/moderation.py
- fixed the messed up warn log formatting
> fix(timeout): fixed the messed up formatting

- cogs/moderation.py
- cogs/prestige.py
- cogs/reportsupport.py
- scam checker with auto kick/mute
- disabled the annoying ai error messages until someone decides to do something
tested and hopefully works in server as well.
> feat/refactor: another batch of goodies

- cogs/moderation.py
some cleanup
- changed some emojis
- cleaned up the scam word list
> fix: wrong kinda emoji situation

- cogs/moderation.py
- cogs/reportsupport.py
- fixed a problem happened after the latest cleanup, cases are getting closed after 19h even though they are not inactive
- automatic "you're muted" message on the muted chat
- logs for automatic inactive case close
- extra roles for the allow witness command
- couple of text changes and grammar fixes
mostly tested, should work
> batch/fix: another urgent fix followed by another batch of goodies

- cogs/moderation.py
this reverts commit 314fe9c6f725862f0b43752bcc9caa80e044d2c6 
- which was about combining mute channel and mute dm messages
> revert(mute): combine the mute messages

- cogs/moderation.py
- cogs/reportsupport.py
- cogs/tools.py
- extra/modals.py
- case logs are finally here, been on the idea list for quite some time
- case channel names have been changed to be similar to the new channel look
- added a quick reminder to report forms, for the toxic reporters
- allowed teachers to use the "ping intersection roles" command, also changed it's description to be easier to understand
- new aliases for unmute command
tested and works. may need some manual channel name changes on the main server.
> feat/refactor(batch): long-awaited feature and some requests

- cogs/communication.py
- extra/reportsupport/applications.py
- extra/slothclasses/view.py
- global chat will automatically change name from a set of pre-defined names
- event and debate channels are combined, debate channels are no longer needed
- added hand kiss option to kiss command
mostly tested, should work.
> feat/refactor(batch): automatic global chat name change and some other stuff

- cogs/communication.py
- cogs/modactivity.py
- extra/slothclasses/view.py
- every gif that was broken in the roleplay commands are now fixed
- global chat name formatting is corrected, it will add the necessary emoji and symbol just like before
- modrep reset message is no longer being deleted
> fix(batch): channel and gif fixes

- cogs/eventmanagement.py
- cogs/moderation.py
- cogs/tools.py
- new hackmute command for muting users who left the server after doing what they did.
- logs for manual unbans.
- moderated nicknames will stick to the user until they actually get unmoderated.
- new invite type and scam links added to the scam checker, should get rid of the recent scam links.
- giveaway manager promotion and demotion commands for event managers.
- invite link timeouts durations got decreased.
- removed some roles and categories from join command.
tested and should work.
> feat/refactor(batch): been a while batch

- cogs/communication.py
- cogs/moderation.py
- cogs/reportsupport.py
- anti-image scam, prototype
- move/disconnect logs, another prototype
- mute/deafon logs, not a prototype
- staff management only command for disabling auto-timeouts for cases
- trial moderator role got restricted
- nitrokick is now scamkick, though aliases will stay
- hwarn now weighs 1.5 points, instead of 2 points
- global name's auto name change duration got decreased
- mod pings will also ping staff managers
- infraction lists failing after ~20 infractions, fixed
- that problem causing cases to not close, related to case logs, fixed
- teacher applicants not getting access to interview voice channel, fixed
mostly tested, needs some large scale testing before I can make sure. :p
> feat/refactor/fix(batch): very very big batch
